//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeBackEnd20221026
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_product_stock
    {
        public string StockID { get; set; }
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<short> Qty { get; set; }
        public string Uom { get; set; }
        public Nullable<short> Price { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public string Country { get; set; }
        public string Baking { get; set; }
        public string Flavor { get; set; }
        public Nullable<bool> Dripbag { get; set; }
        public Nullable<System.DateTime> Timelimit { get; set; }
        public Nullable<byte> Fragrance { get; set; }
        public Nullable<byte> Sour { get; set; }
        public Nullable<byte> Bitter { get; set; }
        public Nullable<byte> Sweet { get; set; }
        public Nullable<byte> STRONG { get; set; }
        public string Method { get; set; }
        public string ImgA { get; set; }
        public string ImgB { get; set; }
        public string ImgC { get; set; }
        public string ImgD { get; set; }
        public Nullable<short> Weight { get; set; }
    }
}
